number of panels: 4

left_panel:
  minsize: 300 # 180 great for <=3, otherwise 300
  width: 500   # 260 great for <=3, otherwise 400

date_formatter: "%Y-%m-%d\n%H:%M:%S"

status_mapping:
  # Positive codes: Pass states
  3:
    label: "Pass"
    marker: null
    description: "Data passed all quality checks"
  
  2:
    label: "Pass after Process"
    marker: null
    description: "Data passed after processing/correction"

  
  # Negative codes: Problem states

  -899:
    label: "Range check (auto)"
    marker:
      color: white
      edgecolor: red
      style: "d"
      size: 15
    description: "Value outside of valid range"

  -850:
    label: "Change of rate (auto)"
    marker:
      color: red
      edgecolor: red
      style: "d"
      size: 15
    description: "Value exceeding specific variable 'change of rate' value with respect to previous timestamp"

  -499:
    label: "Suspect"
    marker:
      color: white
      edgecolor: black
      style: "o"
      size: 15
    description: "Data manually flagged as suspect"

  -450:
    label: "Fail"
    marker:
      color: red
      edgecolor: red
      style: "o"
      size: 15
    description: "Data manually flagged as failed"
  
  -299:
    label: "To Be Fixed"
    marker:
      color: white
      edgecolor: black
      style: "s"
      size: 15
    description: "Data needs manual correction"
  
  -250:
    label: "To Be Interpolated"
    marker:
      color: black
      edgecolor: black
      style: "s"
      size: 15
    description: "Data needs interpolation"

